services:
  tts_bot:
    build: .
    image: custom-tts-bot:latest
    container_name: discord_tts_bot
    env_file:
      - path: .env
        required: false
    network_mode: "container:gluetun"
    restart: unless-stopped
    volumes:
      - ./bot.py:/app/bot.py

  rhvoice:
    image: ghcr.io/aculeasis/rhvoice-rest:latest
    container_name: local_rhvoice
    restart: unless-stopped
    ports:
      - "5002:8080"
    environment:
      THREADED: "1"
      RHVOICE_FCACHE: "1"
      RHVOICE_FCACHE_LIFETIME: "168"